### ISSUE TITLE
Hide error when reconnecting?

### ISSUE THREAD

**Issue by NLZ** [Rudoal/mdownloader#10]
When a download fails and retries it still prints the error trace.
Would it make sense to hide it, and maybe do a simple on line warning about it?

```
Downloading Kubera | Volume: 3 | Chapter: 160.09 | Title: Special Episode 7: South Pole Expedition (2)
2020-11-22 13:49:59:  96%|██████████████████████████████████████████████████████████▋  | 25/26 [00:14<00:01,  1.63s/it]Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python39\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2020-11-22 13:49:59: 100%|█████████████████████████████████████████████████████████████| 26/26 [00:18<00:00,  1.40it/s]
```

**Comment by Rudoal** [comment]
i guess i can add
