### ISSUE TITLE
Error when there is no alt cover

### ISSUE THREAD

**Issue by NLZ** [Rudoal/mdownloader#11]
```
Traceback (most recent call last):
  File "C:\Users\nlz\Code\mdownloader\mdownloader.py", line 123, in <module>
    beforeMain(args.id, args.language, args.directory, args.type, args.save_format, args.folder, args.covers)
  File "C:\Users\nlz\Code\mdownloader\mdownloader.py", line 105, in beforeMain
    main(id, language, directory, type, save_format, folder, covers)
  File "C:\Users\nlz\Code\mdownloader\components\main.py", line 94, in main
    typeChecker(id, language, route, type, save_format, make_folder, covers)
  File "C:\Users\nlz\Code\mdownloader\components\main.py", line 18, in typeChecker
    downloadBatch(id, language, route, type, save_format, make_folder, covers)
  File "C:\Users\nlz\Code\mdownloader\components\downloader.py", line 234, in downloadBatch
    json_file.core(1)
  File "C:\Users\nlz\Code\mdownloader\components\jsonmaker.py", line 247, in core
    self.saveCovers()
  File "C:\Users\nlz\Code\mdownloader\components\jsonmaker.py", line 193, in saveCovers
    cover_url = c["url"]
TypeError: string indices must be integers
```

The cover download option (-c save) throws this when a title has no alt covers listed, like [9012](https://mangadex.org/api/v2/title/9012/covers).
But there are titles, where there is only one alt cover, like [50185](https://mangadex.org/api/v2/title/50185/covers) (which is the same as the main cover under different url).

**Comment by Rudoal** [comment]
ffs, fixed in 2.7.4
