### ISSUE TITLE
v2.7.6 is broken

### ISSUE THREAD

**Issue by NLZ** [Rudoal/mdownloader#13]
You probably already noticed the issue, but when I try to download a title (default or specified parameter), it handles it as chapter, and renames the title to 'gb'.

And if I specify the type to chapter it throws an error:
```
Traceback (most recent call last):
  File "C:\Users\nlz\Code\mdownloader\mdownloader.py", line 126, in <module>
    beforeMain(args.id, args.language, args.directory, args.type, args.save_format, args.folder, args.covers)
  File "C:\Users\nlz\Code\mdownloader\mdownloader.py", line 108, in beforeMain
    main(id, language, directory, type, save_format, folder, covers)
  File "C:\Users\nlz\Code\mdownloader\components\main.py", line 83, in main
    fileDownloader(id, language, route, type, save_format, make_folder, covers)
  File "C:\Users\nlz\Code\mdownloader\components\main.py", line 65, in fileDownloader
    typeChecker(id, language, route, type, save_format, make_folder, covers)
  File "C:\Users\nlz\Code\mdownloader\components\main.py", line 22, in typeChecker
    bulkDownloader(id, '', route, 0, save_format, make_folder, '')
  File "C:\Users\nlz\Code\mdownloader\components\downloader.py", line 218, in bulkDownloader
    name = data["user"]["username"]
KeyError: 'user'
```

**Comment by Rudoal** [comment]
Oh ffs, fixed in v2.7.7
